# Generated by Django 4.1.5 on 2023-01-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restorans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('adress', models.TextField()),
                ('phone', models.TextField()),
                ('rate', models.TextField()),
                ('range_money', models.TextField()),
                ('type_cook', models.TextField()),
                ('photo_one', models.TextField()),
                ('photo_two', models.TextField()),
            ],
        ),
    ]
